
server:
  port: ${vcap.application.port:9091}

spring:
#   redis:
#        host: localhost
#        port: 6379
   datasource:
        url: jdbc:mysql://mysqldb:3306/db_example
#        url: jdbc:mysql://localhost:3306/db_example
        username: rranjan
        password: rranjan01
   jpa:
        generate-ddl: true

 
#eureka:
#  client:
#    serviceUrl:
#
#     defaultZone: ${vcap.services.eureka-service.credentials.uri:http://eureka:8761}/eureka/

#---
#spring:
  #profiles: cloud
#eureka:
#  instance:
#  hostname: ${APPLICATION_DOMAIN}
#  nonSecurePort: 80


#Wild guess below
#coreservice11.ribbon.eureka.enabled: true
