#apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
      tier: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb
        tier: mysqldb
    spec:
      containers:
      - image: gcr.io/rajnewproj/mysqlnew:V1
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysqldb
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /data/db
#          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
