kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysqlpvc
  labels: 
    app: mysql
    lab: kuber-lab2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
