apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    lab: kuber-lab2
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels: 
        app: mysqldb
        lab: kuber-lab2
    spec:
      containers: 
      - name: mysqldb
        image: srranjan/mysqlnew:V1
        imagePullPolicy: IfNotPresent
        resources:
          limits :
            cpu: 0.5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
        - name: MYSQL_USER
          value: rranjan
        - name: MYSQL_PASSWORD
          value: rranjan01
        - name: MYSQL_DATABASE
          value: db_example
        ports: 
        - containerPort: 3306
          name: mysqldb
        volumeMounts:
          # name must match the volume name below
        - name: mysql-persistent-volume
          # mount path within the container
          mountPath: /var/lib/mysql
          #mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim
